### ISSUE TITLE
On Startup Root Needed 

### ISSUE THREAD

**Issue by geogod42** [sergiomafra/iniarduino#2]
When I have first started up the script I will get this:
`$ bash: /usr/local/bin/iniarduino: Permission denied`
Running it as root will fix this but yield an error later in the script

**Comment by sergiomafra** [comment]
Sorry for being late to respond.

It is possible that your user does not have permission to execute the script.
Try changing it to 755.

`sudo chmod 755 /usr/local/bin/iniarduino`

This will probably fix your permissions issue.

What is the later error? Can you copy and paste it here?

**Comment by geogod42** [comment]
Yep, this fixes this. Great script btw Thanks!
